// AUTO-GENERATED by scripts/textures/build-textures.py — do not edit.
// Per-body texture rungs and the one mean luminance every rung of a
// body shares (data/textures/README.md § Size ladder).

export interface TextureLadderRow {
  /** Widths this body ships, ascending; the last is its master. */
  readonly rungs: readonly number[];
  /** Sphere-weighted mean linear luminance of the top rung. */
  readonly meanLuminance: number;
}

export const TEXTURE_LADDER: Readonly<Record<string, TextureLadderRow>> = {
  callisto: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.049952 },
  dione: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.20746 },
  earth: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.062722 },
  enceladus: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.225797 },
  europa: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.315024 },
  ganymede: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.179134 },
  iapetus: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.163293 },
  io: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.262267 },
  jupiter: { rungs: [1024, 2048, 3601], meanLuminance: 0.358355 },
  mars: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.129191 },
  mercury: { rungs: [1024, 2048, 4096, 6132], meanLuminance: 0.03051 },
  mimas: { rungs: [1024, 2048, 4096, 6356], meanLuminance: 0.233705 },
  moon: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.299922 },
  neptune: { rungs: [1024, 1800], meanLuminance: 0.290918 },
  pluto: { rungs: [1024, 2048, 4096, 5926], meanLuminance: 0.179515 },
  rhea: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.182652 },
  saturn: { rungs: [1024, 2048, 2880], meanLuminance: 0.577222 },
  tethys: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.193779 },
  titan: { rungs: [1024, 2048, 4040], meanLuminance: 0.256504 },
  triton: { rungs: [1024, 2048, 4096, 8192], meanLuminance: 0.325081 },
  venus: { rungs: [1024, 1800], meanLuminance: 0.298114 },
};
