// Which rung of a body's texture ladder to hold, from the live viewport.
// The rungs themselves are generated by the texture build — see
// `texture-ladder-generated.ts` and `README.md` § Texture tier selection.

import { TEXTURE_LADDER } from './texture-ladder-generated';

/**
 * Fraction of the resident rung's width at which the NEXT rung starts
 * loading. Without it a swap begins only once the body has already
 * outgrown what is resident, so the map is visibly soft for however long
 * the fetch takes and the arrival reads as a sharpening pop. At 0.75 the
 * higher rung is normally resident before it is needed.
 */
export const TEXTURE_TIER_LEAD = 0.75;

/**
 * Texels a body's map needs to put one texel on every device pixel of its
 * disc. An equirect map spans 360° of longitude across its width while the
 * visible hemisphere is 180°, so the disc diameter is covered by W/2
 * texels — hence the factor of two.
 *
 * `physPx` is the body's TRUE projected diameter in CSS px, which already
 * folds in distance, viewport size AND field of view; `pixelRatio` is the
 * one thing it does not carry.
 */
export function requiredMapWidth(physPx: number, pixelRatio: number): number {
  return 2 * physPx * pixelRatio;
}

/** The rungs a body ships, ascending, or null if it has no map at all. */
export function rungsOf(body: string): readonly number[] | null {
  return TEXTURE_LADDER[body]?.rungs ?? null;
}

/**
 * The one mean linear luminance every rung of a body shares, measured at
 * build from its top rung. Null for a body with no map.
 *
 * Shared rather than per-rung because the renderer divides it out of
 * `uSurfaceLuminance`: if two rungs disagreed even slightly, every tier
 * swap would step the disc's brightness on a body whose magnitude is
 * physically pinned (`emission/README.md` § Two disc means).
 */
export function meanLuminanceOf(body: string): number | null {
  return TEXTURE_LADDER[body]?.meanLuminance ?? null;
}

/**
 * Fraction of the resident rung's width below which a body has shrunk far
 * enough to give that rung up.
 *
 * Paired with `TEXTURE_TIER_LEAD` to leave a dead band: a body is only
 * dropped once the demand is well under what it holds, and it lands where
 * neither rule fires again. Without the gap the two thresholds would meet and
 * a body sitting near a boundary would swap every frame.
 */
export const TEXTURE_TIER_DROP = 0.3;

/**
 * The rung to hold now. `resident` is the width already loaded, or null
 * before the first load.
 *
 * Four rules. Rules 3 and 4 are one mechanism — a hysteresis band with the
 * demand somewhere inside it — rather than a preference and its exception:
 *
 * 1. **Round up.** The smallest rung at or above what the display can
 *    resolve, clamped to the body's top rung — a body simply has no rung
 *    above its master, and asking for one would 404 every frame.
 * 2. **Lead the swap.** Once the demand reaches `TEXTURE_TIER_LEAD` of the
 *    resident width, move to the next rung up even though the resident one
 *    still satisfies rule 1.
 * 3. **Hold across the band.** Between `TEXTURE_TIER_DROP` and
 *    `TEXTURE_TIER_LEAD` of the resident width, keep what is loaded. Most
 *    camera motion lives here and costs nothing.
 * 4. **Drop when the body has shrunk well past it**, to the smallest rung at
 *    or above `demand / TEXTURE_TIER_LEAD`. Dividing by the lead is what
 *    guarantees the landing rung does not immediately re-trigger rule 2 — the
 *    result is a fixed point, and the test iterates it to prove that.
 *
 * Downgrading is the CHEAP direction and giving it up was the mistake this
 * corrects. An 8192 → 1024 drop uploads 2.8 MB to free 176 MB; the reverse
 * uploads 179 MB. And it is not a quality loss: rule 1 says the smallest rung
 * at or above the demand is *sufficient*, so anything above it is memory the
 * screen cannot show. Without this, a body that stays on screen keeps
 * whatever rung it once reached forever — it is drawn every frame, so the
 * eviction pass may never touch it, and eight planets left at 5 px would pin
 * ~1.4 GB that nothing could reclaim.
 */
export function selectRung(
  body: string,
  requiredWidth: number,
  resident: number | null,
): number | null {
  const rungs = rungsOf(body);
  if (rungs === null || rungs.length === 0) return null;
  const top = rungs[rungs.length - 1];
  const roundUp = (w: number) => rungs.find((r) => r >= w) ?? top;

  const want = roundUp(requiredWidth);
  if (resident === null) return want;
  if (requiredWidth >= TEXTURE_TIER_LEAD * resident) {
    return Math.max(want, rungs.find((r) => r > resident) ?? top);
  }
  if (requiredWidth < TEXTURE_TIER_DROP * resident) {
    return Math.min(resident, roundUp(requiredWidth / TEXTURE_TIER_LEAD));
  }
  return resident;
}
