// Which rung of a body's texture ladder to hold, from the live viewport.
// The rungs themselves are generated by the texture build — see
// `texture-ladder-generated.ts` and `README.md` § Texture tier selection.

import { TEXTURE_LADDER } from './texture-ladder-generated';

/**
 * Fraction of the resident rung's width at which the NEXT rung starts
 * loading. Without it a swap begins only once the body has already
 * outgrown what is resident, so the map is visibly soft for however long
 * the fetch takes and the arrival reads as a sharpening pop. At 0.75 the
 * higher rung is normally resident before it is needed.
 */
export const TEXTURE_TIER_LEAD = 0.75;

/**
 * Texels a body's map needs to put one texel on every device pixel of its
 * disc. An equirect map spans 360° of longitude across its width while the
 * visible hemisphere is 180°, so the disc diameter is covered by W/2
 * texels — hence the factor of two.
 *
 * `physPx` is the body's TRUE projected diameter in CSS px, which already
 * folds in distance, viewport size AND field of view; `pixelRatio` is the
 * one thing it does not carry.
 */
export function requiredMapWidth(physPx: number, pixelRatio: number): number {
  return 2 * physPx * pixelRatio;
}

/** The rungs a body ships, ascending, or null if it has no map at all. */
export function rungsOf(body: string): readonly number[] | null {
  return TEXTURE_LADDER[body]?.rungs ?? null;
}

/**
 * The one mean linear luminance every rung of a body shares, measured at
 * build from its top rung. Null for a body with no map.
 *
 * Shared rather than per-rung because the renderer divides it out of
 * `uSurfaceLuminance`: if two rungs disagreed even slightly, every tier
 * swap would step the disc's brightness on a body whose magnitude is
 * physically pinned (`emission/README.md` § Two disc means).
 */
export function meanLuminanceOf(body: string): number | null {
  return TEXTURE_LADDER[body]?.meanLuminance ?? null;
}

/**
 * The rung to hold now. `resident` is the width already loaded, or null
 * before the first load.
 *
 * Three rules, and only the third is about hysteresis:
 *
 * 1. **Round up.** The smallest rung at or above what the display can
 *    resolve, clamped to the body's top rung — a body simply has no rung
 *    above its master, and asking for one would 404 every frame.
 * 2. **Lead the swap.** Once the requirement reaches `TEXTURE_TIER_LEAD`
 *    of the resident width, move to the next rung up even though the
 *    resident one still satisfies rule 1.
 * 3. **Never downgrade.** Retreating from a body would otherwise spend an
 *    upload to make the image worse. One-way ratcheting also makes thrash
 *    structurally impossible, which is why there is no matching
 *    down-hysteresis: release belongs to eviction, not to selection.
 */
export function selectRung(
  body: string,
  requiredWidth: number,
  resident: number | null,
): number | null {
  const rungs = rungsOf(body);
  if (rungs === null || rungs.length === 0) return null;
  const top = rungs[rungs.length - 1];

  let want = rungs.find((r) => r >= requiredWidth) ?? top;
  if (resident !== null && requiredWidth >= TEXTURE_TIER_LEAD * resident) {
    const next = rungs.find((r) => r > resident) ?? top;
    if (next > want) want = next;
  }
  return resident === null ? want : Math.max(want, resident);
}
