// Entry point: pnpm run measure:band-resolved. See README.md.

import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import {
  decodeRecordColumn,
  readCatalogHeader,
  wholeRecordSpan,
} from '../catalog/record/catalog-pure';
import { DEFAULT_CATALOG_MANIFEST, readCatalogBuffer } from '../catalog/catalog-lookup';
import { REPO_ROOT } from '../util/paths';
import {
  GALACTIC_CENTRE_PC,
  GALACTIC_NORTH_POLE_ICRS,
  ICRS_TO_GAL_M3,
} from '../../src/client/galactic/galactic-coords';
import {
  SOL_GALACTOCENTRIC_PC,
  type Vec3,
  galacticDirection,
  sightlineColumn,
} from '../../src/client/milkyway/milkyway-column-pure';
import { SB_ZERO_POINT } from '../../src/client/hdr/emission/emission-pure';
import {
  RESOLVED_HOLE_BANDS,
  RESOLVED_HOLE_SHELLS,
  type ResolvedHoleTable,
  resolvedHoleIndex,
  resolvedHoleGridOf,
} from '../../src/client/milkyway/calibration/resolved-fraction-pure';
import { RESOLVED_HOLE_CATALOGUE_RECORDS } from '../../src/client/milkyway/calibration/resolved-hole-table';
import {
  type CapSurfaceBrightness,
  MIN_STARS_PER_CELL,
  type Rotation3,
  type StarColumns,
  buildHoleCells,
  capSurfaceBrightness,
  holeLight,
  resolvedHoleTableFromCells,
  type ShellTotal,
  shellHoleLight,
  shellTotals,
} from './resolved-light-pure';

const TABLE_MODULE = 'src/client/milkyway/calibration/resolved-hole-table.ts';

async function loadColumns(manifestPath: string): Promise<StarColumns> {
  const buffer = await readCatalogBuffer(manifestPath);
  const header = readCatalogHeader(buffer);
  const view = new DataView(buffer);
  const span = wholeRecordSpan(header);
  const column = (field: 'x' | 'y' | 'z' | 'absmag') => {
    const out = new Float32Array(header.count);
    decodeRecordColumn(view, span, field, out);
    return out;
  };
  return { x: column('x'), y: column('y'), z: column('z'), absmag: column('absmag'), count: header.count };
}

function unit(v: { x: number; y: number; z: number }): Vec3 {
  const n = Math.hypot(v.x, v.y, v.z);
  return [v.x / n, v.y / n, v.z / n];
}

const mag = (flux: number) => -2.5 * Math.log10(flux);
const fmt = (n: number, digits = 4) => n.toFixed(digits);

type Caps = Record<'galacticCentre' | 'northGalacticPole', CapSurfaceBrightness>;

function renderModule(records: number, caps: Caps, table: ResolvedHoleTable): string {
  const rows: string[] = [];
  for (let b = 0; b < RESOLVED_HOLE_BANDS; b++) {
    const row = Array.from({ length: RESOLVED_HOLE_SHELLS }, (_, s) =>
      fmt(table.values[resolvedHoleIndex(s, b)]));
    rows.push('  ' + row.join(', ') + ',');
  }
  rows[rows.length - 1] = rows[rows.length - 1].replace(/,$/, '');
  const cap = (c: CapSurfaceBrightness) =>
    `{ magArcsec2: ${fmt(c.magArcsec2)}, stars: ${c.stars} }`;
  return `// AUTO-GENERATED by scripts/milkyway-calibration/measure-resolved-light.ts — do not edit by hand.
// Regenerate: pnpm run measure:band-resolved. Layout: resolved-fraction-pure.ts.

export const RESOLVED_HOLE_CATALOGUE_RECORDS = ${records};

export const RESOLVED_CATALOGUE_CAP = {
  galacticCentre: ${cap(caps.galacticCentre)},
  northGalacticPole: ${cap(caps.northGalacticPole)},
} as const;

/** ${RESOLVED_HOLE_BANDS} rows of |sin b| bands, each ${RESOLVED_HOLE_SHELLS} distance shells. */
export const RESOLVED_HOLE_VALUES: readonly number[] = [
${rows.join('\n')}
];
`;
}

function printShells(title: string, rows: readonly ShellTotal[], removed: readonly number[]): void {
  console.log(`\n## ${title}`);
  console.log('  shell (pc)            stars      catalogue      model   resolved   table');
  for (const c of rows) {
    console.log(
      `  ${fmt(c.innerPc, 0).padStart(6)}–${fmt(c.outerPc, 0).padEnd(6)} ${String(c.stars).padStart(9)}` +
        `  ${c.catalogue.toExponential(3).padStart(11)}  ${c.model.toExponential(3).padStart(10)}` +
        `  ${fmt(c.model > 0 ? c.catalogue / c.model : 0, 3).padStart(6)}   ${fmt(removed[c.shell] / c.model, 3)}`,
    );
  }
}

async function main(): Promise<void> {
  const manifestArg = process.argv.indexOf('--manifest');
  const manifestPath =
    manifestArg >= 0 ? resolve(process.argv[manifestArg + 1]) : DEFAULT_CATALOG_MANIFEST;
  const stars = await loadColumns(manifestPath);
  const manifest = JSON.parse(await readFile(manifestPath, 'utf-8')) as { totalBytes: number };
  console.log(`catalogue: ${stars.count.toLocaleString()} records, ${manifest.totalBytes.toLocaleString()} bytes\n`);

  console.log('## Cap surface brightness (de-extincted, 10° caps)');
  const caps: Caps = {
    galacticCentre: capSurfaceBrightness(stars, unit(GALACTIC_CENTRE_PC)),
    northGalacticPole: capSurfaceBrightness(stars, unit(GALACTIC_NORTH_POLE_ICRS)),
  };
  for (const [name, row] of Object.entries(caps)) {
    console.log(`  ${name.padEnd(18)} ${fmt(row.magArcsec2)} mag/arcsec²  over ${row.stars.toLocaleString()} stars`);
  }

  const m = ICRS_TO_GAL_M3.elements;
  // three stores column-major; row-major rows are (e0,e3,e6), (e1,e4,e7), (e2,e5,e8).
  const icrsToGal: Rotation3 = [m[0], m[3], m[6], m[1], m[4], m[7], m[2], m[5], m[8]];
  const cells = buildHoleCells(stars, icrsToGal);
  const table = resolvedHoleTableFromCells(cells);

  console.log(`\n## The table — rows are |sin b| bands (plane first), columns the distance shells; a cell under ${MIN_STARS_PER_CELL} stars takes its shell's all-sky share`);
  const shellLabels = cells.filter((c) => c.band === 0).map((c) => fmt(c.innerPc, 0).padStart(5));
  console.log('  ' + shellLabels.join(' '));
  for (let b = 0; b < RESOLVED_HOLE_BANDS; b++) {
    const row = Array.from({ length: RESOLVED_HOLE_SHELLS }, (_, s) =>
      fmt(table.values[resolvedHoleIndex(s, b)], 3).padStart(5));
    console.log('  ' + row.join(' '));
  }
  console.log('\n  stars per cell, same layout');
  for (let b = 0; b < RESOLVED_HOLE_BANDS; b++) {
    console.log('  ' + cells.filter((c) => c.band === b).map((c) => String(c.stars).padStart(5)).join(' '));
  }

  printShells(
    'All sky, by shell — resolved share observed, and what the sampled table removes',
    shellTotals(cells), shellHoleLight(cells, table));

  const totalCatalogue = cells.reduce((s, c) => s + c.catalogue, 0);
  const totalHole = cells.reduce((s, c) => s + holeLight(c, table), 0);
  const totalModel = cells.reduce((s, c) => s + c.model, 0);
  console.log('\n## Light budget over the tabulated volume');
  console.log(`  Σ catalogue ${totalCatalogue.toExponential(4)}   Σ hole ${totalHole.toExponential(4)}  (${fmt(totalHole / totalCatalogue, 4)} of the catalogue)`);
  console.log(`  Σ model ${totalModel.toExponential(4)}   hole / model ${(totalHole / totalModel).toExponential(4)}  = ${fmt(-2.5 * Math.log10(1 - totalHole / totalModel), 4)} mag of the band's light inside it`);

  console.log('\n## Dust-free columns from Sol — model total, unresolved, the hole, and the catalogue cap');
  const sightlines: [keyof Caps, Vec3][] = [
    ['galacticCentre', galacticDirection(0, 0)],
    ['northGalacticPole', galacticDirection(0, 90)],
  ];
  for (const [name, dir] of sightlines) {
    const total = sightlineColumn(SOL_GALACTOCENTRIC_PC, dir, { dustEnabled: false, resolvedHole: null });
    const unresolved = sightlineColumn(SOL_GALACTOCENTRIC_PC, dir, { dustEnabled: false, resolvedHole: resolvedHoleGridOf(table) });
    console.log(
      `  ${name.padEnd(18)} total ${fmt(SB_ZERO_POINT + mag(total), 3)}  unresolved ${fmt(SB_ZERO_POINT + mag(unresolved), 3)}` +
        `  hole ${fmt(SB_ZERO_POINT + mag(total - unresolved), 3)}  catalogue cap ${fmt(caps[name].magArcsec2, 3)}`,
    );
  }

  const out = resolve(REPO_ROOT, TABLE_MODULE);
  if (stars.count < RESOLVED_HOLE_CATALOGUE_RECORDS && !process.argv.includes('--force')) {
    console.log(
      `\nNot written: this build has ${stars.count.toLocaleString()} records against the ` +
        `${RESOLVED_HOLE_CATALOGUE_RECORDS.toLocaleString()} the committed table was measured on. ` +
        'A shallower catalogue is not the one the band ships against; pass --force to overwrite anyway.',
    );
    return;
  }
  await writeFile(out, renderModule(stars.count, caps, table));
  console.log(`\nWrote ${out}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
