// Blackbody → linear-sRGB lookup table generator. TypeScript port of
// research/star-spectral-rendition/blackbody_color.py. Builds a 256-entry
// RGB table over B-V ∈ [BV_MIN, BV_MAX] by quantising the chromaticity
// chain in blackbody-lut-pure.ts.
//
// Runs at build time via `pnpm run build:lut`. The output module
// src/client/star-pipeline/blackbody-lut-data.ts is committed; the byte signature is
// pinned by vitest so any change here forces a deliberate update on both
// sides.
//
// See docs/science-stellar-modelling.md § "Star colour calibration" and
// research/star-spectral-rendition/README.md § Tier 1.

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import {
  BV_MAX,
  BV_MIN,
  LUT_SIZE,
  ballesterosTeff,
  blackbodyToLinearSrgb,
  bvAtIndex,
} from './blackbody-lut-pure';

export { BV_MAX, BV_MIN, LUT_SIZE, ballesterosTeff, bvAtIndex };

// ---- LUT build --------------------------------------------------------

/**
 * Build the 256-entry RGB LUT as a flat Uint8Array of 768 bytes (R, G, B
 * × 256). Each row's Teff = Ballesteros(bvAtIndex(i)), with Planck → CIE
 * 1931 → linear sRGB → peak-normalise → uint8 quantise. Quantising in
 * linear light costs at most 0.91% on any component (the smallest
 * peak-normalised component across the table is 0.189, at the red end).
 */
export function buildLut(): Uint8Array {
  const out = new Uint8Array(LUT_SIZE * 3);
  for (let i = 0; i < LUT_SIZE; i++) {
    const bv = bvAtIndex(i);
    const teff = ballesterosTeff(bv);
    const [r, g, b] = blackbodyToLinearSrgb(teff);
    out[i * 3 + 0] = Math.round(r * 255);
    out[i * 3 + 1] = Math.round(g * 255);
    out[i * 3 + 2] = Math.round(b * 255);
  }
  return out;
}

/**
 * Sample the LUT at a (possibly out-of-range) B-V value, linearly
 * interpolating between adjacent entries. Mirrors the GPU's linear
 * filtering on the LUT sampler texture — pure helper so the shader's
 * sampling path can be pinned by vitest.
 */
export function sampleLut(
  lut: Uint8Array,
  bv: number,
): [number, number, number] {
  const t = ((bv - BV_MIN) / (BV_MAX - BV_MIN)) * (LUT_SIZE - 1);
  const tc = Math.min(LUT_SIZE - 1, Math.max(0, t));
  const i0 = Math.floor(tc);
  const i1 = Math.min(LUT_SIZE - 1, i0 + 1);
  const f = tc - i0;
  const r = lut[i0 * 3 + 0] * (1 - f) + lut[i1 * 3 + 0] * f;
  const g = lut[i0 * 3 + 1] * (1 - f) + lut[i1 * 3 + 1] * f;
  const b = lut[i0 * 3 + 2] * (1 - f) + lut[i1 * 3 + 2] * f;
  return [r, g, b];
}

// ---- CLI entry: write src/client/star-pipeline/blackbody-lut-data.ts ----

function formatBytesAsLines(bytes: Uint8Array, perLine = 24): string {
  const lines: string[] = [];
  for (let i = 0; i < bytes.length; i += perLine) {
    const chunk = Array.from(bytes.slice(i, i + perLine))
      .map((b) => b.toString().padStart(3, ' '))
      .join(', ');
    lines.push('  ' + chunk + ',');
  }
  // Trim the trailing comma on the last line.
  const last = lines.length - 1;
  lines[last] = lines[last].replace(/,$/, '');
  return lines.join('\n');
}

function renderModule(bytes: Uint8Array): string {
  return `// AUTO-GENERATED by scripts/colour/blackbody-lut.ts — do not edit by hand.
// Regenerate via: pnpm run build:lut
//
// 256-entry blackbody → linear-sRGB lookup indexed by B-V over [${BV_MIN}, ${BV_MAX}].
// Each entry's Teff is derived via Ballesteros 2012; chromaticity is the
// Planck spectrum at that Teff through CIE 1931 2° (Wyman 2013 multi-
// Gaussian fits) and the sRGB D65 transform, peak-normalised. Values are
// LINEAR light, not gamma-encoded — the star shader renormalises each
// sample to luminance 1 and the tone-map pass owns the only sRGB encode.
// See scripts/colour/blackbody-lut.ts and
// docs/science-stellar-modelling.md § "Star colour calibration".

export const LUT_SIZE = ${LUT_SIZE};
export const BV_MIN = ${BV_MIN};
export const BV_MAX = ${BV_MAX};

/** Flat RGB bytes — R, G, B repeated ${LUT_SIZE} times. ${bytes.length} bytes. */
export const LUT_BYTES: Uint8Array = new Uint8Array([
${formatBytesAsLines(bytes)}
]);
`;
}

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const out = resolve(here, '..', '..', 'src/client/star-pipeline/blackbody-lut-data.ts');
  const bytes = buildLut();
  await writeFile(out, renderModule(bytes));
  console.log(`Wrote ${out} (${bytes.length} LUT bytes)`);
}

const isCli = import.meta.url === `file://${process.argv[1]}`;
if (isCli) {
  void main();
}
