// Every src/client class field typed `| null` and written after construction, with what its null means.

const IN_FLIGHT = 'in flight: null is "none running", its own answer';
const SELECTION = 'selection: null is "nothing selected", its own answer';
const CACHE = 'cache: null is "nothing seen yet", and the owner recomputes on it';
const RESOURCE = 'resource: built on first use or attach, nulled by dispose; readers skip on null';
const SEAM = 'install seam: null is "nothing installed"';

export const NULLABLE_FIELDS: Readonly<Record<string, string>> = {
  'BinaryOrbitField.focalChainIdx': CACHE,
  'BinaryOrbitField.lastFocalIdx': CACHE,
  'EclipsePhotometryField.lastNowMs': CACHE,
  'HeldOrbitPose.held': IN_FLIGHT,
  'AimController.navigate': IN_FLIGHT,
  'AimController.observe': IN_FLIGHT,
  'InputController.pointerDownAt': IN_FLIGHT,
  'InputController.twoFingerAngle': IN_FLIGHT,
  'InputController.rollDrag': IN_FLIGHT,
  'InputController.activePointer': IN_FLIGHT,
  'TrackballSettle.detachDom': SEAM,
  'FocalRides.rideFocalIdx': CACHE,
  'FocalRides.movingIdx': CACHE,
  'FocusController.focused': SELECTION,
  'FocusController.vector': SELECTION,
  'FocusController.planetSystemHost': SELECTION,
  'FocusController.focusLerpState': IN_FLIGHT,
  'ObserveControls.activePointerId': IN_FLIGHT,
  'ObserveTransition.state': IN_FLIGHT,
  'WarpController.state': IN_FLIGHT,
  'ChartLabels.ctx': IN_FLIGHT,
  'ChartLabels.layer': RESOURCE,
  'ChartLabels.conLayer': RESOURCE,
  'ChartLabels.glyphLayer': RESOURCE,
  'ChartLabels.variableEligible': CACHE,
  'ChartLabels.binaryEligible': CACHE,
  'ConstellationBoundaryLayer.lineSegments': RESOURCE,
  'ConstellationBoundaryLayer.fade': RESOURCE,
  'ConstellationBoundaryLayer.fadeWindow': CACHE,
  'ConstellationFigureLayer.lineSegments': RESOURCE,
  'ConstellationFigureLayer.positions': RESOURCE,
  'FloatingOrigin.policy': SEAM,
  'SceneAdaptation.landed': CACHE,
  'SceneAdaptation.lastNowMs': CACHE,
  'LocalBubbleShell.geometry': RESOURCE,
  'LocalBubbleShell.mesh': RESOURCE,
  'LgPeakCache.at': CACHE,
  'BandPeakCache.at': CACHE,
  'HudOverlay.onSolLabelClick': RESOURCE,
  'HudOverlay.onGcLabelClick': RESOURCE,
  'RenderGate.detachDom': SEAM,
  'RenderGate.lastWake': CACHE,
  'RenderGate.lastDecision': CACHE,
  'OrbitRingsLayer.ps': SELECTION,
  'ProbeField.hiddenIdx': SELECTION,
  'PlanetBodyField.hideIdx': SELECTION,
  'PlanetBodyField.lastDimNowMs': CACHE,
  'VirtualClock.frameT': IN_FLIGHT,
  'StarLocalCluster.hostMemberIdx': SELECTION,
  'StarPipeline.hiddenStar': SELECTION,
  'StarLocalCluster.chainFocalIdx': CACHE,
  'StarLocalCluster.chainBinaries': CACHE,
  'Stellata.orbitFrameTick': SEAM,
  'Stellata.orbitFramePort': SEAM,
  'Typeahead.pendingQuery': IN_FLIGHT,
  'PendingClickDispatcher.pending': IN_FLIGHT,
  'WebGpuExtinctionPrepass.positions': RESOURCE,
  'WebGpuExtinctionPrepass.order': RESOURCE,
  'WebGpuExtinctionPrepass.av': RESOURCE,
  'WebGpuExtinctionPrepass.stamps': RESOURCE,
  'WebGpuExtinctionPrepass.refillTable': RESOURCE,
  'WebGpuExtinctionPrepass.fillKernel': RESOURCE,
  'WebGpuExtinctionPrepass.refillKernel': RESOURCE,
  'WebGpuExtinctionPrepass.dispatchOrder': RESOURCE,
  'WebGpuExtinctionPrepass.lastView': CACHE,
  'WebGpuHdrPipeline.rt': RESOURCE,
  'WebGpuHdrPipeline.summation': RESOURCE,
  'WebGpuHdrPipeline.resolveQuad': RESOURCE,
  'WebGpuHdrPipeline.resolveMaterial': RESOURCE,
  'WebGpuHdrPipeline.blackTexture': RESOURCE,
  'WebGpuLuminanceReduction.landed': IN_FLIGHT,
  'WebGpuLuminanceReduction.latest': CACHE,
  'WebGpuSummationPass.target': RESOURCE,
  'StarCompaction.kernels': RESOURCE,
  'StarCompaction.plainKernels': RESOURCE,
};
