// Generates the .omp/rules/*.md omp reads every turn: the bd prime context as
// an always-apply rule, and the forbidden comment patterns as a TTSR trigger.
// `--check` verifies the deterministic one without regenerating it.

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCommentRules } from './comment-rules';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const RULES_DIR = join(ROOT, '.omp/rules');

const MARKER = '<!-- AUTO-GENERATED by pnpm run build:omp-rules -->';

/**
 * A TTSR rule whose `condition` regexes are matched against the arguments of
 * an edit or write as the model streams them, so a forbidden comment is
 * refused at the moment it is authored rather than at `git commit`.
 *
 * Two things here are load-bearing. `interruptMode: tool-only` — these
 * patterns match ordinary prose about beads, and an `always` rule would abort
 * the turn every time a bead id appeared in a reply. And the globs are
 * path-shaped rather than `*.ts`, because a bare extension glob matches on
 * basename and would fire on the suites whose fixtures are deliberately full
 * of bead ids. `src/` and `scripts/` is the same scope the vitest suite walks.
 */
function commentRuleFile(): string {
  const rules = loadCommentRules(ROOT);

  const conditions = rules
    .map((rule) => `  - ${JSON.stringify(rule.flags.includes('i')
      ? `(?i)${rule.pattern}`
      : rule.pattern)}`)
    .join('\n');

  const scope = ['src', 'scripts']
    .flatMap((dir) => ['ts', 'js', 'py'].map((ext) => `${dir}/**/*.${ext}`))
    .flatMap((glob) => [`tool:edit(${glob})`, `tool:write(${glob})`])
    .join(', ');

  const body = readFileSync(join(ROOT, 'scripts/hooks/comment-rule-body.md'), 'utf8');

  return `---
description: Forbidden code-comment patterns, refused as they are written
scope: ${JSON.stringify(scope)}
interruptMode: tool-only
condition:
${conditions}
---

${MARKER}

${body.trim()}

Patterns, by name:

${rules.map((rule) => `- ${rule.name}`).join('\n')}
`;
}

/**
 * `bd prime --full` as an always-apply rule. Claude Code needs prime-guard
 * because its SessionStart payload is truncated to 2KB; omp has no such limit
 * and injects an always-apply body into the system prompt, which compaction
 * rebuilds rather than summarises. So the gate is unnecessary here — the
 * content is simply always present.
 */
function primeRuleFile(): string {
  const prime = execFileSync(process.env.PRIME_GUARD_BD ?? 'bd', ['prime', '--full'], {
    cwd: ROOT,
    encoding: 'utf-8',
    maxBuffer: 8 * 1024 * 1024,
  });
  if (prime.trim() === '') throw new Error('bd prime --full produced nothing');

  return `---
description: bd workflow context and the persistent project memories
alwaysApply: true
---

${MARKER}

${prime.trim()}
`;
}

function main(): void {
  const check = process.argv.includes('--check');
  const commentRule = commentRuleFile();
  const commentPath = join(RULES_DIR, 'code-comments.md');

  if (check) {
    const onDisk = readFileSync(commentPath, 'utf8');
    if (onDisk !== commentRule) {
      throw new Error(
        `${commentPath} is stale. Run: pnpm run build:omp-rules`,
      );
    }
    return;
  }

  mkdirSync(RULES_DIR, { recursive: true });
  writeFileSync(commentPath, commentRule);
  writeFileSync(join(RULES_DIR, 'bd-prime.md'), primeRuleFile());
}

main();
